function opt_b = cal_bias_SVR(z, n, l);
m = floor(n/2);
l = floor(n*l);
Y = zeros(n,1);
xi = zeros(n,1);
c = m - l - 1;
err = zeros(2*l+1,1);
B = zeros(2*l+1,1);
[sortedz, d] = sort(z, 'ascend');
for i = m-l:m+l;
    Y(1:i) = -1;
    Y(i+1:n) = 1;
    b = (sortedz(i) + sortedz(i+1))/2;
    xi = abs(Y - sortedz + b);
    err(i - c) = sum(xi);
    B(i-c) = b;
end;
dex = find(err == min(err));
opt_b = B(dex(1));